### ISSUE TITLE
Substring of hash not working

### ISSUE THREAD

**Issue by edouard-lopez** [kbukum/webpack-file-changer#1]
Thanks for your plugin and the simplicity of it

### Env

```
├─ webpack-file-changer@1.0.0
├─ webpack@1.14.0
```

### Context

My project is structured like
```

├── index.html
├── src
│   ├── app.js
│   ├── components
│   └── index.html
└── webpack.config.js
```

### Goal

I'm trying to copy `src/index.html` to `./index.html` and insert the hash to the latter:

    <script src="static/app.min.js"></script>
to

    <script src="static/app-5237375c.min.js"></script>

### Issue

This work fine is I insert the full `[hash]` however it fails when I attempt to use a substring of the hash `[hash:8]` with the following code

               const FileChanger = require('webpack-file-changer');

    module.exports = {
	    plugins: [
		new FileChanger({
			move: [{
				from: path.resolve(__dirname, './src', 'index.html'),
				to: path.resolve(__dirname, 'index.html')
			}],
			change: [{
				file: path.resolve(__dirname, 'index.html'),
				parameters: {
					'app\\.min\\.js': 'app.[hash:8].min.js'
				}
			}]
		})
        ]
    }

I got the string `[hash:8]` instead of the hash value in the output:

    <script src="static/app.[hash:8].min.js"></script>

**related:** webpack/webpack#86

**Comment by kbukum** [comment]
Hello edouard,

Thank you for the given information. 

I will add this feature and inform to you.

**Comment by kbukum** [comment]
@edouard-lopez added new features to the https://github.com/kbukum/webpack-file-changer plugin.

You can use [hash:id] to replace. [hash:id] is get hash of chunk by chunk index.

I think you mean that.

Also you can use before and after callback functions after move files or replace content of files.
