### ISSUE TITLE
Replacing an everchanging string

### ISSUE THREAD

**Issue by Moghul** [kbukum/webpack-file-changer#2]
I have a static HTML file which gets handled server-side. For this reason, I can't actually move it from its place. I'm trying to use this plugin to update the references to the bundles because I'm fingerprinting them.

The plugin works, but I'm having some trouble figuring out how to change the hash in the file. Let me clarify...

Say I start out with this:
`<script type="text/javascript" src="/path/to/bundle.js"></script>`

I run webpack with your plugin and I end up with this:
`<script type="text/javascript" src="/path/to/hashgoeshere.bundle.js"></script>`

Which is great. However, next time the hash changes, how can I update that hash and make it
`<script type="text/javascript" src="/path/to/differenthash.bundle.js"></script>`

Here's what I'm doing right now:
```
        new FileChangerPlugin({
            change: [{
                file: path.resolve(__filename, '/path/to/file.html'),
                parameters: {'bundle\\.js' : '[renderedHash:0].bundle.js'}
            }]
        })
```

EDIT: Well, it looks like you're just using the Javascript String.replace() method. I'll leave this open until I can figure it out how to do it for myself and close it when I do.

**Comment by Moghul** [comment]
Yep, figured it out.

For the string "/path/to/hashgoeshere.bundle.js" I would use

`\\/path\\/to\\/\\S+\\.bundle\\.js`

as a key in my parameters.

That \\S+ is where the hash goes. Everything else is the path and file name. Yes, this RegExp will match anything in there so if you use this method, make sure the contents of your RegExp are very specific to that path. The only downside is that you always have to have something there for your "hash". Having nothing there will make this fail.

I am by no means a pro at regular expressions so if you have a cleaner, better solution, feel free to share.

**Comment by kbukum** [comment]
Hi Moghul,

Actually it is not just replace. I have to know which `stats` property will change. You can see changing parameters method at below. 

```typescript
    static getParameters(stats: any, parameters: {[key: string]: string}) {
        if(parameters) {
            for(let key in parameters) {
                if(parameters.hasOwnProperty(key)) {
                    let value = parameters[key];
                    if(typeof value === "string") {
                        let hashResult = value.match(WebpackUtility.hashPattern);
                        if(hashResult != null) {
                            value = value.replace(WebpackUtility.hashPattern, stats.hash);
                        }
                        let hasIdResult = value.match(WebpackUtility.hashAndIdPattern);
                        if(hasIdResult != null) {
                            value = value.replace(WebpackUtility.hashAndIdPattern, stats.compilation.chunks[hasIdResult[2]].hash);
                        }
                        let renderedHashIdResult = value.match(WebpackUtility.renderedHashAndIdPattern);
                        if(renderedHashIdResult != null) {
                            value = value.replace(WebpackUtility.renderedHashAndIdPattern, stats.compilation.chunks[renderedHashIdResult[2]].renderedHash);
                        }
                    }
                    parameters[key] = value;
                }
            }
        }
        return parameters;
    }
```

Actually its possible to add a new feature for custom conversions like at below. What do you think about this feature ? 

```typescript
     new FileChangerPlugin({
            change: [{
                file: path.resolve(__filename, '/path/to/file.html'),
                parameters: {
                       'bundle\\.js' :  function (key: string, stats: any) {
                               // This function is used for custom conversion.
                              return converted_data;
                      } 
                }
            }]
        })
```

You can check the code to click https://github.com/kbukum/webpack-file-changer/blob/master/src/util/WebpackUtility.ts

If its not answered about your questions please clarify me.

Have a nice day.

**Comment by Moghul** [comment]
I'm not sure what `stats` is, I'll have to check that out in a minute.

The problem I'm seeing with the latter code snippet is that the `bundle\\.js` would not also select the hash in front of it. After the first build, it would become `hash1.bundle.js` and the parameter key would not be selecting the `hash1.`, making the next time you run the code `hash1.hash2.bundle.js`.

EDIT: Ok, so, for some reason I thought that last snippet was already implemented. I'm not sure what the  possibilities are for the feature you suggested. I assume you do whatever you want with the `key` & `stats` (whatever stats is), and then return a string to replace the matches found with `bundle\\.js`.

It doesn't fix the `hash1.hash2.bundle.js` problem.

EDIT2: Ok, so... stats is this huge object that has... something to do with Webpack.
I guess the 'stats property' I'm changing is `renderedHash`. I always give it the same renderedHash index every time `[renderedHash:0]` depending on which bundle we're talking about.

So technically I could use the key I provided in my first reply, get the match string back, dig through the stats, and get the value I want, and return a different string, or:

```
        new FileChangerPlugin({
            change: [{
                file: path.resolve(__filename, '/path/to/myfile.html'),
                parameters: {
                    'public\\/\\S+\\.code\\.bundle\\.js': 'public/[renderedHash:0].code.bundle.js'
                }
            }]
        })
```

Which is exactly what I'm doing right now and it works.

**Comment by kbukum** [comment]
I understand what you mean. The plugin use the key as regex. That's mean you can include the regex for the previous hash.  You solution is right. If your problem solved than I will close the issue.

Note: I will add custom conversion feature ASAP.
