### ISSUE TITLE
Webpack 4.0.0 - doesn't seem to work with watch mode

### ISSUE THREAD

**Issue by Moghul** [kbukum/webpack-file-changer#3]
Webpack 4.0.0 can watch for changes by either calling webpack with the --watch flag or by adding 

```
    watch: true,
    watchOptions: {
        aggregateTimeout: 1000,
        ignored: vendor
    }
```

to your config file. In both scenarios, replacement never happens.

This plugin in my config: 
```
        new FileChangerPlugin({
            change: [{
                file: templateDirectory + '/Statistics.html',
                parameters: {
                    'statistics\\/\\S+\\.statistics\\.bundle\\.css': 'statistics/[renderedHash:1].statistics.bundle.css',
                    'statistics\\/\\S+\\.statistics\\.bundle\\.js': 'statistics/[renderedHash:1].statistics.bundle.js',
                    'statistics\\/\\S+\\.vendor\\.bundle\\.js': 'statistics/[renderedHash:2].vendor.bundle.js'
                }
            }, {
                file: templateDirectory + '/Compare.html',
                parameters: {
                    'statistics\\/\\S+\\.statistics\\.bundle\\.css': 'statistics/[renderedHash:1].statistics.bundle.css',
                    'statistics\\/\\S+\\.compare\\.bundle\\.js': 'statistics/[renderedHash:0].compare.bundle.js',
                    'statistics\\/\\S+\\.vendor\\.bundle\\.js': 'statistics/[renderedHash:2].vendor.bundle.js'
                }
            }]
        })
```

The first build in the 'watch' setup works, and so does building without watching. It's the rebuild that breaks it.

**Comment by kbukum** [comment]
Could you create a simple sample to include your config on the github and share it with me ? Then I can test it.

**Comment by Moghul** [comment]
To clarify, do you just want my config file to work on it or do you want a sample project that includes all the stuff used/accessed by my config file? Or do you want a basic project that uses webpack and your plugin?

Because for sure I don't have the time to set up a copy of my project and I also can't share the project with you since it's not open-source and not public. The last one also seems like I could just share the head in the html file with you and the webpack.config.js

**Comment by Moghul** [comment]
Alright I've created a sample project and added you as a collaborator. I'll take it down once we're done with it. https://github.com/Moghul/file-changer-watch-test

Just get webpack 4.0.0, webpack-cli and your plugin installed, and run the config file. Then, once it's ready to listen, go to /Source/Scripts/statistics.js and edit x to be a different value.

There will be a new bundle in /Dist with an updated name and code, but the .html file will not have changed. Run the config file again, and it's fixed.

I really need that watch feature working.

EDIT: It also seems like it doesn't work with `mode: 'production'`, but it does work with `mode: 'development'`

**Comment by kbukum** [comment]
changed file-changer-watch-test project and fixed problem.
- changed server mode as production.
- added before change method. 
- Also you can add after method and delete old built js file.

**Comment by Moghul** [comment]
Thanks man, I really appreciate it! I'll try it in my project as well, but I'll list here what you did to make it work:

```
        new FileChangerPlugin({
            change: [{
                file: templateDirectory + '/NonMovableFile.html',
                parameters: {
                    'Dist\\/.*\\.statistics\.bundle\\.js': 'Dist/[renderedHash:0].statistics.bundle.js'
                },
                before: function (stats, change) {
                    console.log(change);
                    change.parameters['Dist\\/.*\\.statistics\.bundle\\.js'] = 'Dist/' + stats.hash + '.statistics.bundle.js';
                    console.log(change);
                }
            }]
        })
```

Also, in my actual config, I have cleanup set up. I just put in the minimum.

EDIT:
So... This doesn't actually work for me.
I changed the logs a little bit and I'm getting this lovely output:

```
{ file: '/path/to/my/NonMovableFile.html',
  parameters: 
   { 'Dist\\/statistics\\.bundle\\.\\S+\\.js': 'Dist/statistics.bundle.1c9ea85e19eb570cad13.js',
     'Dist\\.statistics.bundle\\/.\\S+\\.js': 'Dist/statistics.bundle.e17ce30edc99df9d11e2.js' },
  before: [Function: before] }
================================================================= // Added by me
Replacing in /path/to/my/NonMovableFile.html.html: Dist/statistics.bundle.1c9ea85e19eb570cad13.js => Dist/statistics.bundle.1c9ea85e19eb570cad13.js

```
That last output is correct, it doesn't get changed. Switching `before` with `after` doesn't fix it either.

PS: is there a reason you changed the file structure?
PPS: How would this work with 2 key-value pairs in `parameters` ?

**Comment by kbukum** [comment]
Hi,

Both keys are different. when before method executed then added key is different from the defined key.

I fixed problem in project and pushed it to the your repository. 

You need to be careful about the searched value in index.html. Before all defined value should match your regex which is defined as key in parameters.

 ` 
<script type="text/javascript" src="../../Dist/statistics.bundle.0209fa8926c56e28d7da.js"></script>
`

and plugin configuration like 


```
  new FileChangerPlugin({
            change: [{
                file: templateDirectory + '/NonMovableFile.html',
                parameters: {
                    'Dist\\/statistics\.bundle\\..*\\.js': ''
                },
                before: function (stats, change) {
                    change.parameters['Dist\\/statistics\.bundle\\..*\\.js'] = 'Dist/statistics.bundle.' + stats.hash + '.js';
                }
            }]
})
```

As you can see the defined key in parameters is just used to function call `before` and `after` functions. In this functions you can change parameters programatically. You can change hash value programatically in before function. You can to write `stats`. `stats` is holds all states about build which is provide by webpack.

**Comment by Moghul** [comment]
The keys are only different because I had to switch the names of the bundles around. I already took that into account. The regular build still works. I'll try and take a look at what you did and see if it fixes it for me.

(Hopefully) Final edit: 

```
        new FileChangerPlugin({
            change: [{
                file: templateDirectory + '/NonMovableFile.html',
                parameters: {
                    'whatever regex matches your string': ''
                },
                before: function (stats, change) {
                    change.parameters['same regex as above'] = 'replacement string';
                }
            }, {
                file: templateDirectory + '/AnotherNonMovableFile.html',
                parameters: {
                    'first regex goes here': '',
                    'second regex goes here': ''
                },
                before: function (stats, change) {
                    change.parameters['first regex'] = 'first replacement';
                    change.parameters['second regex'] = 'second replacement';
                }
            }]
        })
```

What the documentation doesn't tell you, and it should, is **You don't have to use `stats.hash`, you can use `[renderedHash:index]` in your replacements to do multiple replacements.**. Also, in order to use the `before` function to do your replacements when `--watch` is enabled, the replacements in `parameters` must be empty strings.

Thanks for all the help, I hope this helps someone at some point. Going to take the sample project down and close this now.
